import { User, Subject, Session, Review, Message, Notification } from "./types";

// Mock Subjects Data
export const mockSubjects: Subject[] = [
  // Computer Science
  {
    id: "s1",
    name: "Data Structures & Algorithms",
    category: "Computer Science",
    department: "CSE",
  },
  {
    id: "s2",
    name: "Web Development",
    category: "Computer Science",
    department: "CSE",
  },
  {
    id: "s3",
    name: "Machine Learning",
    category: "Computer Science",
    department: "CSE",
  },
  {
    id: "s4",
    name: "Database Management",
    category: "Computer Science",
    department: "CSE",
  },
  {
    id: "s5",
    name: "Python Programming",
    category: "Computer Science",
    department: "CSE",
  },

  // Mathematics
  {
    id: "s6",
    name: "Calculus",
    category: "Mathematics",
    department: "Mathematics",
  },
  {
    id: "s7",
    name: "Linear Algebra",
    category: "Mathematics",
    department: "Mathematics",
  },
  {
    id: "s8",
    name: "Statistics",
    category: "Mathematics",
    department: "Mathematics",
  },

  // Business
  {
    id: "s9",
    name: "Marketing Management",
    category: "Business",
    department: "BBA",
  },
  {
    id: "s10",
    name: "Financial Accounting",
    category: "Business",
    department: "BBA",
  },
  {
    id: "s11",
    name: "Business Analytics",
    category: "Business",
    department: "BBA",
  },

  // Engineering
  {
    id: "s12",
    name: "Electronics",
    category: "Engineering",
    department: "ECE",
  },
  {
    id: "s13",
    name: "Digital Circuits",
    category: "Engineering",
    department: "ECE",
  },
  {
    id: "s14",
    name: "Mechanical Design",
    category: "Engineering",
    department: "Mech",
  },

  // Languages
  {
    id: "s15",
    name: "English Literature",
    category: "Languages",
    department: "Arts",
  },
  { id: "s16", name: "French", category: "Languages", department: "Arts" },
  { id: "s17", name: "Spanish", category: "Languages", department: "Arts" },
];

// Mock Users Data
export const mockUsers: User[] = [
  {
    id: "u1",
    email: "aara@alliance.edu.in",
    password: "password123",
    name: "Nuzhath Aara",
    universityId: "AU2021CSE001",
    department: "Computer Science",
    year: 3,
    bio: "Passionate about AI/ML and web development. Love helping others learn programming!",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aara",
    points: 850,
    minRate: 0,
    preferredMode: "both",
    subjectsToTeach: [
      {
        subjectId: "s1",
        proficiency: 5,
        description: "Competitive programmer, CodeChef 5-star",
      },
      {
        subjectId: "s2",
        proficiency: 4,
        description: "Full-stack developer with React & Node.js",
      },
      {
        subjectId: "s5",
        proficiency: 5,
        description: "Python expert, data science enthusiast",
      },
    ],
    subjectsToLearn: [
      {
        subjectId: "s3",
        urgency: 4,
        description: "Need help with neural networks",
      },
      {
        subjectId: "s10",
        urgency: 2,
        description: "Want to understand financial statements",
      },
    ],
    availability: [
      { dayOfWeek: 1, startTime: "14:00", endTime: "18:00" },
      { dayOfWeek: 3, startTime: "14:00", endTime: "18:00" },
      { dayOfWeek: 5, startTime: "10:00", endTime: "16:00" },
    ],
    rating: 4.8,
    totalReviews: 24,
    joinedAt: "2023-08-15",
  },
  {
    id: "u2",
    email: "priya.patel@alliance.edu.in",
    password: "password123",
    name: "Priya Patel",
    universityId: "AU2020BBA002",
    department: "Business Administration",
    year: 4,
    bio: "BBA student specializing in marketing and finance. Happy to help with business subjects!",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    points: 620,
    minRate: 50,
    preferredMode: "video",
    subjectsToTeach: [
      {
        subjectId: "s9",
        proficiency: 5,
        description: "Marketing major with internship experience",
      },
      {
        subjectId: "s10",
        proficiency: 4,
        description: "Strong foundation in accounting",
      },
      {
        subjectId: "s11",
        proficiency: 3,
        description: "Learning business analytics tools",
      },
    ],
    subjectsToLearn: [
      {
        subjectId: "s2",
        urgency: 3,
        description: "Want to build a business website",
      },
      {
        subjectId: "s8",
        urgency: 5,
        description: "Need help with statistical analysis",
      },
    ],
    availability: [
      { dayOfWeek: 2, startTime: "16:00", endTime: "20:00" },
      { dayOfWeek: 4, startTime: "16:00", endTime: "20:00" },
    ],
    rating: 4.6,
    totalReviews: 18,
    joinedAt: "2023-09-20",
  },
  {
    id: "u3",
    email: "amit.kumar@alliance.edu.in",
    password: "password123",
    name: "Amit Kumar",
    universityId: "AU2022ECE003",
    department: "Electronics & Communication",
    year: 2,
    bio: "ECE student interested in embedded systems and IoT. Also good at mathematics!",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amit",
    points: 380,
    minRate: 0,
    preferredMode: "in-person",
    subjectsToTeach: [
      {
        subjectId: "s12",
        proficiency: 4,
        description: "Strong in analog and digital electronics",
      },
      {
        subjectId: "s13",
        proficiency: 4,
        description: "Good with digital logic design",
      },
      {
        subjectId: "s6",
        proficiency: 5,
        description: "Mathematics topper in school",
      },
    ],
    subjectsToLearn: [
      {
        subjectId: "s1",
        urgency: 4,
        description: "Want to improve DSA for placements",
      },
      {
        subjectId: "s5",
        urgency: 3,
        description: "Learning Python for automation",
      },
    ],
    availability: [
      { dayOfWeek: 1, startTime: "17:00", endTime: "21:00" },
      { dayOfWeek: 3, startTime: "17:00", endTime: "21:00" },
      { dayOfWeek: 6, startTime: "10:00", endTime: "18:00" },
    ],
    rating: 4.4,
    totalReviews: 12,
    joinedAt: "2024-01-10",
  },
  {
    id: "u4",
    email: "sara.jones@alliance.edu.in",
    password: "password123",
    name: "Sara Jones",
    universityId: "AU2021ART004",
    department: "Arts & Humanities",
    year: 3,
    bio: "Literature major with a passion for languages. Fluent in English, French, and Spanish.",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sara",
    points: 450,
    minRate: 100,
    preferredMode: "both",
    subjectsToTeach: [
      {
        subjectId: "s15",
        proficiency: 5,
        description: "English literature major, creative writing",
      },
      {
        subjectId: "s16",
        proficiency: 4,
        description: "Studied in France for a year",
      },
      {
        subjectId: "s17",
        proficiency: 3,
        description: "Conversational Spanish",
      },
    ],
    subjectsToLearn: [
      {
        subjectId: "s2",
        urgency: 2,
        description: "Want to create a blog website",
      },
      {
        subjectId: "s9",
        urgency: 3,
        description: "Interested in content marketing",
      },
    ],
    availability: [
      { dayOfWeek: 2, startTime: "14:00", endTime: "17:00" },
      { dayOfWeek: 4, startTime: "14:00", endTime: "17:00" },
      { dayOfWeek: 5, startTime: "15:00", endTime: "19:00" },
    ],
    rating: 4.9,
    totalReviews: 15,
    joinedAt: "2023-11-05",
  },
  {
    id: "u5",
    email: "arjun.reddy@alliance.edu.in",
    password: "password123",
    name: "Arjun Reddy",
    universityId: "AU2020CSE005",
    department: "Computer Science",
    year: 4,
    bio: "Final year CS student, placement ready! Specializing in ML and data science.",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun",
    points: 1200,
    minRate: 0,
    preferredMode: "both",
    subjectsToTeach: [
      {
        subjectId: "s3",
        proficiency: 5,
        description: "ML researcher, published papers",
      },
      {
        subjectId: "s1",
        proficiency: 5,
        description: "Cracked multiple tech interviews",
      },
      {
        subjectId: "s4",
        proficiency: 4,
        description: "SQL expert, NoSQL experience",
      },
      {
        subjectId: "s8",
        proficiency: 4,
        description: "Strong statistical background",
      },
    ],
    subjectsToLearn: [
      {
        subjectId: "s11",
        urgency: 2,
        description: "Want to learn business side of tech",
      },
    ],
    availability: [
      { dayOfWeek: 0, startTime: "10:00", endTime: "18:00" },
      { dayOfWeek: 6, startTime: "10:00", endTime: "18:00" },
    ],
    rating: 4.95,
    totalReviews: 42,
    joinedAt: "2023-06-12",
  },
];

// Mock Sessions Data
export const mockSessions: Session[] = [
  {
    id: "sess1",
    tutorId: "u1",
    learnerId: "u3",
    subjectId: "s1",
    scheduledAt: "2024-01-20T14:00:00",
    duration: 60,
    mode: "in-person",
    location: "Library Room 203",
    status: "completed",
    notes: "Covered arrays and linked lists",
    amount: 0,
    pointsAwarded: 50,
    createdAt: "2024-01-18T10:00:00",
  },
  {
    id: "sess2",
    tutorId: "u2",
    learnerId: "u1",
    subjectId: "s10",
    scheduledAt: "2024-01-22T16:00:00",
    duration: 90,
    mode: "video",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    status: "confirmed",
    amount: 75,
    pointsAwarded: 0,
    createdAt: "2024-01-19T14:30:00",
  },
  {
    id: "sess3",
    tutorId: "u5",
    learnerId: "u2",
    subjectId: "s8",
    scheduledAt: "2024-01-25T10:00:00",
    duration: 120,
    mode: "in-person",
    location: "Study Hall A",
    status: "pending",
    amount: 0,
    pointsAwarded: 0,
    createdAt: "2024-01-20T09:00:00",
  },
  // Additional completed sessions for realistic data
  {
    id: "sess4",
    tutorId: "u2",
    learnerId: "u4",
    subjectId: "s7",
    scheduledAt: "2024-01-15T14:00:00",
    duration: 60,
    mode: "video",
    status: "completed",
    notes: "Physics mechanics problems",
    amount: 50,
    pointsAwarded: 50,
    createdAt: "2024-01-13T10:00:00",
  },
  {
    id: "sess5",
    tutorId: "u3",
    learnerId: "u1",
    subjectId: "s6",
    scheduledAt: "2024-01-12T16:00:00",
    duration: 90,
    mode: "in-person",
    location: "Library Room 101",
    status: "completed",
    notes: "Calculus integration techniques",
    amount: 0,
    pointsAwarded: 75,
    createdAt: "2024-01-10T14:00:00",
  },
  {
    id: "sess6",
    tutorId: "u4",
    learnerId: "u5",
    subjectId: "s11",
    scheduledAt: "2024-01-10T10:00:00",
    duration: 120,
    mode: "video",
    status: "completed",
    notes: "Marketing fundamentals",
    amount: 100,
    pointsAwarded: 100,
    createdAt: "2024-01-08T09:00:00",
  },
  {
    id: "sess7",
    tutorId: "u5",
    learnerId: "u3",
    subjectId: "s2",
    scheduledAt: "2024-01-08T14:00:00",
    duration: 60,
    mode: "in-person",
    location: "Computer Lab 2",
    status: "completed",
    notes: "Python basics and data types",
    amount: 0,
    pointsAwarded: 50,
    createdAt: "2024-01-06T10:00:00",
  },
  {
    id: "sess8",
    tutorId: "u1",
    learnerId: "u2",
    subjectId: "s3",
    scheduledAt: "2024-01-05T15:00:00",
    duration: 90,
    mode: "video",
    status: "completed",
    notes: "React hooks and state management",
    amount: 75,
    pointsAwarded: 75,
    createdAt: "2024-01-03T12:00:00",
  },
  {
    id: "sess9",
    tutorId: "u2",
    learnerId: "u5",
    subjectId: "s10",
    scheduledAt: "2024-01-03T16:00:00",
    duration: 60,
    mode: "in-person",
    location: "Study Room B",
    status: "completed",
    notes: "Organic chemistry reactions",
    amount: 50,
    pointsAwarded: 50,
    createdAt: "2024-01-01T14:00:00",
  },
  {
    id: "sess10",
    tutorId: "u3",
    learnerId: "u4",
    subjectId: "s12",
    scheduledAt: "2023-12-28T14:00:00",
    duration: 120,
    mode: "video",
    status: "completed",
    notes: "Digital electronics and logic gates",
    amount: 0,
    pointsAwarded: 100,
    createdAt: "2023-12-26T10:00:00",
  },
  {
    id: "sess11",
    tutorId: "u4",
    learnerId: "u1",
    subjectId: "s14",
    scheduledAt: "2023-12-25T10:00:00",
    duration: 90,
    mode: "in-person",
    location: "Library Discussion Room",
    status: "completed",
    notes: "International economics",
    amount: 75,
    pointsAwarded: 75,
    createdAt: "2023-12-23T09:00:00",
  },
  {
    id: "sess12",
    tutorId: "u5",
    learnerId: "u2",
    subjectId: "s4",
    scheduledAt: "2023-12-20T15:00:00",
    duration: 60,
    mode: "video",
    status: "completed",
    notes: "SQL queries and joins",
    amount: 50,
    pointsAwarded: 50,
    createdAt: "2023-12-18T11:00:00",
  },
];

// Mock Reviews Data
export const mockReviews: Review[] = [
  {
    id: "rev1",
    sessionId: "sess1",
    reviewerId: "u3",
    revieweeId: "u1",
    rating: 5,
    comment:
      "Excellent explanation of data structures! Very patient and helpful.",
    createdAt: "2024-01-20T16:00:00",
  },
  {
    id: "rev2",
    sessionId: "sess4",
    reviewerId: "u4",
    revieweeId: "u2",
    rating: 4,
    comment: "Good session on physics. Could have used more practice problems.",
    createdAt: "2024-01-15T15:30:00",
  },
  {
    id: "rev3",
    sessionId: "sess5",
    reviewerId: "u1",
    revieweeId: "u3",
    rating: 5,
    comment:
      "Amazing at explaining complex calculus concepts! Highly recommend.",
    createdAt: "2024-01-12T18:00:00",
  },
  {
    id: "rev4",
    sessionId: "sess6",
    reviewerId: "u5",
    revieweeId: "u4",
    rating: 5,
    comment: "Very knowledgeable about business and marketing. Great insights!",
    createdAt: "2024-01-10T12:30:00",
  },
  {
    id: "rev5",
    sessionId: "sess7",
    reviewerId: "u3",
    revieweeId: "u5",
    rating: 4,
    comment: "Good Python basics tutorial. Very structured approach.",
    createdAt: "2024-01-08T15:30:00",
  },
  {
    id: "rev6",
    sessionId: "sess8",
    reviewerId: "u2",
    revieweeId: "u1",
    rating: 5,
    comment: "React expert! Learned so much about hooks and best practices.",
    createdAt: "2024-01-05T17:00:00",
  },
  {
    id: "rev7",
    sessionId: "sess9",
    reviewerId: "u5",
    revieweeId: "u2",
    rating: 3,
    comment: "Decent chemistry session, but felt a bit rushed.",
    createdAt: "2024-01-03T17:30:00",
  },
  {
    id: "rev8",
    sessionId: "sess10",
    reviewerId: "u4",
    revieweeId: "u3",
    rating: 4,
    comment: "Clear explanations of digital electronics. Very helpful!",
    createdAt: "2023-12-28T16:30:00",
  },
  {
    id: "rev9",
    sessionId: "sess11",
    reviewerId: "u1",
    revieweeId: "u4",
    rating: 5,
    comment:
      "Excellent economics tutor! Made complex topics easy to understand.",
    createdAt: "2023-12-25T12:00:00",
  },
  {
    id: "rev10",
    sessionId: "sess12",
    reviewerId: "u2",
    revieweeId: "u5",
    rating: 5,
    comment: "SQL master! Taught me everything about database queries.",
    createdAt: "2023-12-20T16:30:00",
  },
  // Additional reviews to match user ratings
  {
    id: "rev11",
    sessionId: "sess1",
    reviewerId: "u1",
    revieweeId: "u3",
    rating: 4,
    comment: "Good student, asked thoughtful questions.",
    createdAt: "2024-01-20T16:30:00",
  },
  {
    id: "rev12",
    sessionId: "sess8",
    reviewerId: "u1",
    revieweeId: "u2",
    rating: 5,
    comment: "Very eager to learn, great discussion!",
    createdAt: "2024-01-05T17:30:00",
  },
  {
    id: "rev13",
    sessionId: "sess9",
    reviewerId: "u2",
    revieweeId: "u5",
    rating: 4,
    comment: "Well-prepared student, good questions about the material.",
    createdAt: "2024-01-03T18:00:00",
  },
  {
    id: "rev14",
    sessionId: "sess10",
    reviewerId: "u3",
    revieweeId: "u4",
    rating: 5,
    comment: "Quick learner, grasped concepts easily.",
    createdAt: "2023-12-28T17:00:00",
  },
  {
    id: "rev15",
    sessionId: "sess11",
    reviewerId: "u4",
    revieweeId: "u1",
    rating: 4,
    comment: "Good engagement during the session.",
    createdAt: "2023-12-25T12:30:00",
  },
];

// Mock Messages Data
export const mockMessages: Message[] = [
  {
    id: "msg1",
    senderId: "u3",
    receiverId: "u1",
    sessionId: "sess1",
    content: "Hi Aara, looking forward to our DSA session!",
    isRead: true,
    createdAt: "2024-01-19T12:00:00",
  },
  {
    id: "msg2",
    senderId: "u1",
    receiverId: "u3",
    sessionId: "sess1",
    content: "Hey Amit! Me too. See you in the library.",
    isRead: true,
    createdAt: "2024-01-19T12:30:00",
  },
];

// Mock Notifications Data
export const mockNotifications: Notification[] = [
  {
    id: "notif1",
    userId: "u1",
    type: "session_request",
    title: "New Session Request",
    message: "Amit Kumar requested a DSA tutoring session",
    isRead: false,
    createdAt: "2024-01-18T10:00:00",
  },
  {
    id: "notif2",
    userId: "u1",
    type: "points_earned",
    title: "Points Earned!",
    message: "You earned 50 points for completing a tutoring session",
    isRead: false,
    createdAt: "2024-01-20T16:00:00",
  },
];
